package com.haaretz.entities;


import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

/**
 * Created by elia.grady on 04/01/2017.
 */
@Entity
@Table(name = "users")
public class User implements Serializable {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  @NotNull
  @Column(unique=true)
  private String phoneNumber;

  @NotNull
  private String name;

  @NotNull
  private String email;

  @NotNull
  private String addressLineStreet;

  @NotNull
  private String addressLineCity;

  @NotNull
  private boolean newsletterSub; // Mouse Newsletter Subscription

  @NotNull
  private boolean perksSub; // Mouse Perks Subscription

  @CreationTimestamp
  private Date created;


  public User() { }

  public User(long id) {
    this.setId(id);
  }

  public Long getId() {
    return id;
  }



  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String fullName) {
    this.name = fullName;
  }

  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getAddressLineStreet() {
    return addressLineStreet;
  }

  public void setAddressLineStreet(String addressLineStreet) {
    this.addressLineStreet = addressLineStreet;
  }

  public String getAddressLineCity() {
    return addressLineCity;
  }

  public void setAddressLineCity(String addressLineCity) {
    this.addressLineCity = addressLineCity;
  }

  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public boolean getNewsletterSub() {
    return newsletterSub;
  }

  public void setNewsletterSub(boolean newsletterSub) {
    this.newsletterSub = newsletterSub;
  }
  public boolean getPerksSub() {
    return perksSub;
  }

  public void setPerksSub(boolean perksSub) {
    this.perksSub = perksSub;
  }


  @Override
  public boolean equals(Object obj) {
    return obj instanceof User && ((User) obj).id == this.id && ((User) obj).getPhoneNumber().equals(this.getPhoneNumber());
  }

  @Override
  public int hashCode() {
    return super.hashCode();
  }

}
